### PR TITLE
support ipaddr/macaddr.4.0.0 interfaces

### PR DESCRIPTION
**Pull request by avsm**
also:
* cleanup warnings in dune's default dev profile (@avsm)
* test with OCaml 4.08.0 (@avsm)

### CODE REVIEW

**Comment by hannesm** [comment]
I briefly looked through this PR, and think:
- it would benefit if different changesets (fix compiler warnings; port to new API) would be different commits
- I dislike disabling of warnings, and prefer to either fix them or leave them alone

**Comment by avsm** [comment]
Good points both; I've pushed fixes as separate commits. Also spotted a minor bug in 1b94f9a82b2839311e55e164154573408e074f0c while fixing the unused bindings warnings that could use some confirmation.

**Comment by hannesm** [comment]
thanks, that looks good to me!

**Comment by avsm** [comment]
Will wait till https://github.com/mirage/arp/pull/16

**Comment by avsm** [comment]
Restarted CI now that arp/ethernet are released

**Pull request merged**
