### PR TITLE
use {= version} constraints for packages

### PR DESCRIPTION
**Pull request by hannesm**
i find this much easier than to rethink when we need to bump versions, and in practise, I'm only really willing to support one version across the repository.

### CODE REVIEW

**Comment by hannesm** [comment]
any opinion on this? @haesbaert @yomimono

**Comment by yomimono** [comment]
Does this `version` get auomatically substituted by `dune-release` or something? I'm failing to find links on this syntax quickly because `version` isn't the best search string.

**Comment by hannesm** [comment]
@yomimono it's in opam (2.0 i assume): https://opam.ocaml.org/doc/Manual.html#pkgvar-version

**Comment by yomimono** [comment]
Ah, OK - I was looking at a different bit of packaging documentation and missed this entirely; thanks for the pointer.  In that case this seems fine, I'll merge it.

**Pull request merged**
